# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Luiz Fernando
tagline:             'Unzkilled Nando'
description:         'Um espaço para compartilhar um pouco do pouco que sei. <br> A place to share a bit of the bit I know :)'
url:                 http://zr0n.github.io
baseurl:             '/blog'
paginate:            5

# About/contact
author:
  name:              Luiz Fernando
  url:               https://facebook.com/TheZiron
  email:             ads.luizfernando@gmail.com

# Custom vars
version:             1.0.0
